import * as z from "zod";

// url: text("url").notNull(),
// title: text("title").notNull(),
// description: text("description").notNull(),
// isFavorite: boolean("isFavorite").default(false),
// aspectRatio: real("aspect_ratio").notNull(),
// width: real("width").notNull(),
// height: real("height").notNull(),
// blurData: text("blur_data").notNull(),
// locationName: varchar("location_name", { length: 255 }),

// // EXIF DATA
// make: varchar("make", { length: 255 }),
// model: varchar("model", { length: 255 }),
// lensModel: varchar("lens_model", { length: 255 }),
// focalLength: real("focal_length"),
// focalLength35mm: real("focal_length_35mm"),
// fNumber: real("f_number"),
// iso: integer("iso"),
// exposureTime: real("exposure_time"),
// exposureCompensation: real("exposure_compensation"),
// gapLatitude: real("gps_latitude"),
// gapLongitude: real("gps_longitude"),
// gpsAltitude: real("gps_altitude"),
// dateTimeOriginal: timestamp("datetime_original"),

export const photoSchema = z.object({
  url: z.string(),
  title: z.string(),
  description: z.string(),
  isFavorite: z.boolean().default(false),
  aspectRatio: z.number(),
  width: z.number(),
  height: z.number(),
  blurData: z.string(),
  locationName: z.string().optional(),
  make: z.string().optional(),
  model: z.string().optional(),
  lensModel: z.string().optional(),
  focalLength: z.number().optional(),
  focalLength35mm: z.number().optional(),
  fNumber: z.number().optional(),
  iso: z.number().optional(),
  exposureTime: z.number().optional(),
  exposureCompensation: z.number().optional(),
  gapLatitude: z.number().optional(),
  gapLongitude: z.number().optional(),
  gpsAltitude: z.number().optional(),
  dateTimeOriginal: z.string().optional(),
});

export type PhotoFormData = z.infer<typeof photoSchema>;
